/* File generated with Shader Minifier 1.1.4
 * http://www.ctrl-alt-test.fr
 */
#ifndef HAL4000_H_
# define HAL4000_H_

const char *hal4000_fs =
 "uniform vec3 V;"
 "float m=V.z*.001;"
 "float s(vec3 f,float x)"
 "{"
   "f.z-=4.5;"
   "vec3 p=vec3(m/2.3,m/1.95,m/2.7),v=sin(p),c=cos(p);"
   "f*=mat3(c.y,v.z*v.y,-v.y*c.z,-v.x*v.y,c.x*c.z+v.x*v.z*c.y,v.z*c.x-v.x*c.z*c.y,c.x*v.y,v.x*c.z-c.x*v.z*c.y,v.z*v.x+c.x*c.z*c.y);"
   "float z=clamp((m-33.)/14.,0.,1.);"
   "x=mix(x,0.,z*z*z);"
   "float i=8.-6.*x,y=3.8*x-2.;"
   "i=mix(i,2.,z*z*z);"
   "f=abs(f);"
   "return pow(pow(f.x,i)+pow(f.y,i)+pow(f.z,i)+y,2.)-x*8.*(f.x*f.x+f.y*f.y);"
 "}"
 "float s(vec3 v)"
 "{"
   "return sin(v.x*5.)/15.+cos(v.x+1.5)/3.+sin(v.z+m)/5.-cos(v.x+2.)*cos(v.z+m)/3.;"
 "}"
 "float p(vec3 m)"
 "{"
   "return length(m-vec3(m.x,s(m)-1.5,m.z));"
 "}"
 "float p(float m,float c)"
 "{"
   "return(m-m*c+1.)*991.;"
 "}"
 "float x(float m)"
 "{"
   "return pow(1.-min(1.,abs(m)),4.);"
 "}"
 "void main()"
 "{"
   "vec2 v=gl_FragCoord.xy/V.xy;"
   "float f=V.x/V.y;"
   "vec2 c=(v-vec2(.5))/vec2(1.,f)*1.4;"
   "float z=0.,i=0.,y=0.,a=0.,l=0.,r=3.1416,n=1.,b,e=.0001,k,o,t=0.,w,h,g;"
   "vec3 d,u=vec3(0.,0.,0.),q=u,F=vec3(0.,1.,12.+max(0.,(m-47.)/8.));"
   "if(m<62.)"
     "{"
       "float C=clamp(m/4.-5.,0.,1.),Z=cos(m/3.1)/2.5+.4,Y=m-22.,X=1.+max(Y*Y*Y/999.,0.)/9.;"
       "h=min(m*m*m/451.,17.7)+.3;"
       "h=mix(h,3.,clamp((m-42.)/5.,0.,1.));"
       "g=30.-fract(m);"
       "for(int W=30;W>0;W--)"
         "d=vec3(c*(1.+g),g),z=max(z,pow(x(-d.y-1.5+C*s(d+vec3(0.,0.,1.))),7.)*-c.y*2.6),g--;"
       "g=4.5+2.*(h-1.)/(h+1.);"
       "for(int W=18;W>0;W--)"
         "d=vec3(c*(2.+g)*X,g),y=max(y,float(s(d,Z)<.1)),i=max(i,x(s(d,Z))/(g-2.6)),g-=4./(h+1.);"
       "y=1.-y;"
       "if(m>46.)"
         "{"
           "d=normalize(vec3(c,1.));"
           "for(int W=0;W<40;W++)"
             "{"
               "b=p(d*n);"
               "if(b<.001)"
                 "break;"
               "n+=b;"
               "if(n>40.)"
                 "break;"
             "}"
           "if(n<40.)"
             "d*=n,q=normalize(vec3(p(d+vec3(e,0.,0.))-p(d-vec3(e,0.,0.)),p(d+vec3(0.,e,0.))-p(d-vec3(0.,e,0.)),p(d+vec3(0.,0.,e))-p(d-vec3(0.,0.,e)))),a=y*pow((length(q+normalize(F-d))-1.1)*max(1.2-length(F-d)/15.,0.),4.);"
         "}"
       "e=2371.;"
       "for(int W=0;W<40;W++)"
         "{"
           "h=m/15.;"
           "if(m>=47.1)"
             "h=3.14+(m-47.1)/20.;"
           "g=fract(h+t);"
           "o=p(c.y,g);"
           "if(o>935.)"
             "{"
               "k=p(c.x,g);"
               "b=fract(sin(pow(floor(k),floor(o)/941.))*e);"
               "if(b>.9985)"
                 "b=distance(vec2(k,o),vec2(floor(k)+.5,floor(o)+.5))*2.,l=max(l,g*min(1.,pow(1.5-b,15.))),l=max(l,g*max(0.,1.-b));"
             "}"
           "e-=.9;"
           "t+=.05;"
         "}"
       "z*=y;"
       "l*=y;"
       "z*=clamp(m/4.-2.5,0.,1.);"
       "l*=clamp(m-31.,0.,1.);"
       "a+=y*max(2.-n/20.,0.)*max(q.z,0.);"
       "a*=pow(clamp(m*2.-93.2,0.,1.),3.);"
       "a=max(0.,a);"
       "u=vec3(l/2.,l*l,sqrt(l))+vec3(0.,a*a,a)+vec3(0.,i*i,i)+vec3(z*z/2.,0.,z);"
       "u*=min(1.,m/4.);"
       "b=2.-clamp(m/4.-12.75,0.,2.);"
       "z=smoothstep(1.,0.,abs(b-length(c)));"
       "u+=vec3(0.,z*z,z);"
       "b=2.-clamp(m/4.-13.5,0.,2.2);"
       "z=smoothstep(b-.1,b+.1,length(c));"
       "u*=1.-z;"
     "}"
   "else"
     "{"
       "if(m<104.)"
         "{"
           "k=min(m,85.)-62.;"
           "w=31.-k;"
           "g=fract(cos(k*3.9)+sin(k)*cos(k*3.7));"
           "if(m<65.)"
             "g=3.-k;"
           "t=length(c)*w;"
           "z=max(0.,.7-min(1.,t));"
           "i=pow(t/99.*float(t<.6),.4)+(.8-t)*float(t<.02);"
           "y=min(1.,pow(max(0.,1.25-t),8.))/(10.-g*3.)+(g*.8+.3)*min(.7,pow(max(0.,.15-t)*9.,12.));"
           "h=c.y*w;"
           "o=.3+.6*cos(cos(9.*(c.x-.4)*r+m/3.)+9.*c.y+m/7.)-.6+.6*cos(cos(9.*c.y*r+m/5.)+9.*(c.x-.4)-m/9.);"
           "z+=clamp(o,0.,1.)/3.*smoothstep(.1,0.,t-.4);"
           "z=mix(z,floor(z*16.)/16.,max(0.,-h));"
           "d=vec3(z+y,y,i);"
           "z=atan(abs(c.x),c.y);"
           "y=smoothstep(.1,0.,t-.53)*clamp(pow(1.3-abs(z),7.)+pow(1.05-abs(.8-z),7.),0.,1.);"
           "a=max(0.,h)*pow(1.-sqrt(abs(t-.55)),10.);"
           "a+=-pow(abs(h),3.)*pow(1.-sqrt(abs(t-.5)),14.);"
           "a*=.5+y/2.;"
           "z=smoothstep(.97,.99,1.035-abs(t-.68));"
           "z-=(1.-g/3.)*.5*float(t>.61)*smoothstep(0.,.01,.685-t);"
           "t=length(c*vec2(.7,1.))*w;"
           "o=1.35-fract(k/24.);"
           "i=0.;"
           "for(int W=1;W<4;W++)"
             "i+=min(.8,max(0.,h)*pow(1.2-sqrt(abs(length(t-o/float(W)))),12.))/((float(W)+.5)/1.5);"
           "i*=y;"
           "a+=i;"
           "F=vec3(a*.9,a*.9,a);"
           "q=.4*sqrt(h+.8)*vec3(z/2.7,z/2.,z/1.5);"
           "u=float(t<2.)*(d+F+q);"
           "u*=min(1.,(m-62.)/4.);"
         "}"
     "}"
   "gl_FragColor=vec4(u,1.);"
 "}";

#endif // HAL4000_H_
